export const product = {
  price: {
    name: "default",
    value: 417,
    currency: "USD",
  },
  _id: "641a5e3a5b838afc4d6cb787",
  name: "Oriental Bronze Pants",
  description:
    "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
  slug: "Oriental-Bronze-Pants",
  categoryId: "a89ef1b0cb2aa29e04012a3c",
  createdById: "9edd6f031d81d0e44e303c13",
  isAvailable: false,
  isHighlighted: false,
  fit: ["young-adult-shoe"],
  gender: ["male"],
  variants: [
    {
      name: "default",
      color: "red",
      size: "XXL",
      quantity: 5,
      _id: "641a5e3a5b838afc4d6cb788",
    },
    {
      name: "Red Small Size",
      color: "red",
      size: "S",
      quantity: 5,
      _id: "641a5e3a5b838afc4d6cb789",
      price: {
        name: "default",
        value: 400,
        currency: "USD",
      },
    },
    {
      name: "Red Medium Size",
      color: "red",
      size: "M",
      quantity: 5,
      _id: "641a5e3a5b838afc4d6cb78a",
      price: {
        name: "default",
        value: 500,
        currency: "USD",
      },
    },
    {
      name: "Red Large Size",
      color: "red",
      size: "L",
      quantity: 0,
      _id: "641a5e3a5b838afc4d6cb78b",
    },
  ],
  reviews: [
    {
      variantId: "a44e1c491a9a0f5f66de51fd",
      userId: "34b36ed6c8e67f481ac2bc6d",
      rating: 5,
      title: "Vitae optio quasi rem odio non exercitationem.",
      body: "Ea doloribus nisi nemo odit nihil porro. Voluptas at iusto nostrum alias temporibus. Pariatur laborum saepe itaque illum error non harum. Dicta minus molestias molestiae tempora hic officiis dolorum quae. Soluta dicta consequuntur non. Facilis explicabo esse eaque sequi distinctio porro libero magnam.",
      isHelpful: 59,
      isNotHelpful: 8,
      archived: false,
    },
    {
      variantId: "a44e1c491a9a0f5f66de51fd",
      userId: "cde58e364f742ac89aee3eb0",
      rating: 1,
      title: "Assumenda velit cum.",
      body: "Impedit dignissimos magnam quo eius ratione laborum quaerat. Quasi ut fugit quidem corporis omnis suscipit. Maxime laudantium accusantium. Porro laudantium atque. Officiis quisquam unde quisquam molestias ea. Atque ipsam amet molestiae ullam ullam esse.",
      isHelpful: 21,
      isNotHelpful: 28,
      archived: false,
    },
    {
      variantId: "a44e1c491a9a0f5f66de51fd",
      userId: "b5dab0f1afdedcdfef0f6127",
      rating: 3,
      title: "Pariatur consequatur laudantium ullam amet dolorum minus.",
      body: "Libero blanditiis odit repudiandae architecto rem earum ea debitis assumenda. Aliquam necessitatibus nam ipsa soluta quibusdam harum. Culpa veritatis sunt numquam numquam dicta libero.",
      isHelpful: 17,
      isNotHelpful: 70,
      archived: false,
    },
  ],
  images: [
    {
      createdById: "9edd6f031d81d0e44e303c13",
      path: "https://loremflickr.com/640/480/abstract",
      alt: "fashion",
      isActive: true,
      isArchived: false,
    },
    {
      createdById: "9edd6f031d81d0e44e303c13",
      path: "https://loremflickr.com/640/480/tehnics",
      alt: "fashion",
      isActive: true,
      isArchived: false,
    },
    {
      createdById: "9edd6f031d81d0e44e303c13",
      path: "https://loremflickr.com/640/480/fashion",
      alt: "fashion",
      isActive: true,
      isArchived: false,
    },
    {
      createdById: "9edd6f031d81d0e44e303c13",
      path: "https://loremflickr.com/640/480/people",
      alt: "fashion",
      isActive: true,
      isArchived: false,
    },
    {
      createdById: "9edd6f031d81d0e44e303c13",
      path: "https://loremflickr.com/640/480/fashion",
      alt: "fashion",
      isActive: true,
      isArchived: false,
    },
    {
      createdById: "9edd6f031d81d0e44e303c13",
      path: "https://loremflickr.com/640/480/tehnics",
      alt: "fashion",
      isActive: true,
      isArchived: false,
    },
    {
      createdById: "9edd6f031d81d0e44e303c13",
      path: "https://loremflickr.com/640/480/fashion",
      alt: "fashion",
      isActive: true,
      isArchived: false,
    },
    {
      createdById: "9edd6f031d81d0e44e303c13",
      path: "https://loremflickr.com/640/480/nightlife",
      alt: "fashion",
      isActive: true,
      isArchived: false,
    },
  ],
  __v: 0,
  createdAt: "2023-03-22T01:47:38.196Z",
  updatedAt: "2023-03-22T01:47:38.196Z",
};
