import { CartItemInterface } from "types/interfaces";

export const cartArr: CartItemInterface[] = [
  {
    productId: {
      price: {
        name: "default",
        value: 607,
        currency: "USD",
      },
      _id: "641a5e3a5b838afc4d6cb79d",
      name: "Generic Soft Chips",
      description:
        "The Football Is Good For Training And Recreational Purposes",
      slug: "Generic-Soft-Chips",
      categoryId: "bbf26feba62c210574dea89e",
      createdById: "9edd6f031d81d0e44e303c13",
      isAvailable: true,
      isHighlighted: false,
      fit: ["infant-shoe"],
      gender: ["male"],
      variants: [
        {
          name: "default",
          color: "lime",
          size: "W-12.5",
          quantity: 10,
          _id: "641a5e3a5b838afc4d6cb79e",
        },
      ],
      reviews: [
        {
          variantId: "b4275c1f0c288bbaff4f0fed",
          userId: "9edd6f031d81d0e44e303c13",
          rating: 2,
          title: "Eveniet laudantium debitis.",
          body: "Veniam veritatis amet consequuntur dolore incidunt. Quisquam officia ea doloribus possimus voluptate. Aliquid cum explicabo nulla molestiae blanditiis.",
          isHelpful: 24,
          isNotHelpful: 90,
          archived: false,
        },
        {
          variantId: "b4275c1f0c288bbaff4f0fed",
          userId: "b5dab0f1afdedcdfef0f6127",
          rating: 3,
          title: "Sed eum iste esse nostrum harum magni.",
          body: "Quod quidem odit maxime consequatur qui provident consequuntur quasi. Quia dolor vero eveniet quisquam exercitationem vero esse accusamus. Ut recusandae cupiditate quae. Aut laborum amet minima incidunt minima asperiores officiis corrupti magni. Doloremque optio at quos provident. Sed ducimus veritatis facere repudiandae reiciendis odit neque quas dolore.",
          isHelpful: 85,
          isNotHelpful: 65,
          archived: false,
        },
        {
          variantId: "b4275c1f0c288bbaff4f0fed",
          userId: "b5dab0f1afdedcdfef0f6127",
          rating: 3,
          title: "Enim optio soluta.",
          body: "Mollitia quaerat in. Itaque necessitatibus iste voluptates velit dignissimos labore. Sapiente perferendis natus facilis tempora.",
          isHelpful: 3,
          isNotHelpful: 34,
          archived: false,
        },
      ],
      images: [
        {
          createdById: "9edd6f031d81d0e44e303c13",
          path: "https://loremflickr.com/640/480/fashion",
          alt: "fashion",
          isActive: true,
          isArchived: false,
        },
        {
          createdById: "9edd6f031d81d0e44e303c13",
          path: "https://loremflickr.com/640/480/fashion",
          alt: "fashion",
          isActive: true,
          isArchived: false,
        },
        {
          createdById: "9edd6f031d81d0e44e303c13",
          path: "https://loremflickr.com/640/480/fashion",
          alt: "fashion",
          isActive: true,
          isArchived: false,
        },
      ],
    },
    variantId: {
      name: "default",
      color: "lime",
      size: "W-12.5",
      quantity: 10,
      _id: "641a5e3a5b838afc4d6cb79e",
    },
    quantity: 1,
  },
  {
    productId: {
      price: {
        name: "default",
        value: 10,
        currency: "USD",
      },
      _id: "641a5e3a5b838afc4d6cb77d",
      name: "Handmade Granite Keyboard",
      description:
        "The Football Is Good For Training And Recreational Purposes",
      slug: "Handmade-Granite-Keyboard",
      categoryId: "0aa8f3cdcab5cd9fcdd1edd7",
      createdById: "9edd6f031d81d0e44e303c13",
      isAvailable: false,
      isHighlighted: false,
      fit: ["youth"],
      gender: ["male"],
      variants: [
        {
          name: "default",
          color: "turquoise",
          size: "XXL",
          quantity: 10,
          _id: "641a5e3a5b838afc4d6cb77e",
        },
      ],
      reviews: [
        {
          variantId: "ee24ebe4fccd2cfb17f4c0ed",
          userId: "b5dab0f1afdedcdfef0f6127",
          rating: 3,
          title:
            "Consequatur alias ut dolor repellat rerum commodi velit accusamus temporibus.",
          body: "Esse autem nisi libero enim dolorum ipsa optio officiis. Eligendi saepe commodi itaque hic. Eos commodi tempora recusandae distinctio impedit dicta quia.",
          isHelpful: 47,
          isNotHelpful: 6,
          archived: false,
        },
        {
          variantId: "ee24ebe4fccd2cfb17f4c0ed",
          userId: "cde58e364f742ac89aee3eb0",
          rating: 1,
          title: "Ratione commodi velit.",
          body: "Rem beatae qui soluta quos ut quia accusamus. Et nulla voluptatibus libero unde voluptatum. Ab rerum consequuntur vel dignissimos doloremque. Quaerat exercitationem nesciunt maiores recusandae odit debitis nisi id. Facere quaerat sint explicabo sequi. Officia id ullam doloremque impedit impedit occaecati.",
          isHelpful: 36,
          isNotHelpful: 62,
          archived: false,
        },
        {
          variantId: "ee24ebe4fccd2cfb17f4c0ed",
          userId: "b5dab0f1afdedcdfef0f6127",
          rating: 3,
          title:
            "Ut eos itaque voluptas alias explicabo aut accusamus reiciendis officiis.",
          body: "Animi maxime dolorem. Quas distinctio eos ipsam similique. Ab dignissimos omnis quos eius esse aut laudantium.",
          isHelpful: 46,
          isNotHelpful: 43,
          archived: false,
        },
      ],
      images: [
        {
          createdById: "9edd6f031d81d0e44e303c13",
          path: "https://loremflickr.com/640/480/fashion",
          alt: "fashion",
          isActive: true,
          isArchived: false,
        },
        {
          createdById: "9edd6f031d81d0e44e303c13",
          path: "https://loremflickr.com/640/480/fashion",
          alt: "fashion",
          isActive: true,
          isArchived: false,
        },
        {
          createdById: "9edd6f031d81d0e44e303c13",
          path: "https://loremflickr.com/640/480/fashion",
          alt: "fashion",
          isActive: true,
          isArchived: false,
        },
      ],
    },
    variantId: {
      name: "default",
      color: "turquoise",
      size: "XXL",
      quantity: 10,
      _id: "641a5e3a5b838afc4d6cb77e",
    },
    quantity: 1,
  },
];
